name: reviewdog
on: [pull_request]
jobs:
  hadolint:
    name: runner / hadolint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: hadolint
        uses: reviewdog/action-hadolint@fix-error
        with:
          github_token: ${{ secrets.github_token }}
          fail_on_error: true
          reporter: github-pr-review # Default is github-pr-check
