name: reviewdog
on: [push]
jobs:
#   dotenv-linter:
#     name: runner / dotenv-linter
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: dotenv-linter/action-dotenv-linter@code-suggestions
#         with:
#           github_token: ${{ secrets.github_token }}
#           reporter: github-code-suggestions
#   reek:
#     name: runner / reek
#     runs-on: ubuntu-latest
#     steps:
#       - name: Check out code
#         uses: actions/checkout@v1
#       - uses: ruby/setup-ruby@v1
#         with:
#           ruby-version: 2.6
#       - name: reek
#         uses: reviewdog/action-reek@v1
#         with:
#           reek_version: gemfile
#           github_token: ${{ secrets.github_token }}
#           reporter: github-pr-review # Default is github-pr-check          
  rubocop:
    name: runner / rubocop
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: rubocop
        uses: reviewdog/action-rubocop@v1
        with:
          rubocop_version: 0.93.1
          github_token: ${{ secrets.github_token }}
          reporter: github-check
